### PR TITLE
Add French Translation

### PR DESCRIPTION
**Pull request by TathanDev**

### CODE REVIEW

**Comment by TathanDev** [comment]
I things i missed

**Review by Efnilite — APPROVED** [review]
Looks good to me! Have you tested to see if everything works?

**Comment by TathanDev** [comment]
yes but i have this bug 
image
It's weird because i translate this part
```yml
play:
  name: <white>Jouer

```

**Comment by Efnilite** [comment]
This doesn't seem to be a problem while switching between English and Dutch, reloading should fix it. Anyway, it looks all good. Thanks for contributing :)

**Pull request merged**
